package com.vtn.social_network.enums;

public enum NotificationType {
    LIKE_POST, LIKE_COMMENT, COMMENT, FRIEND_REQ, FRIEND_ACCEPT, FOLLOWED, BLOCK_SHARED_GROUP, SHARE_POST,
    GROUP_INVITE, GROUP_JOIN_REQUEST, GROUP_JOIN_ACCEPT, GROUP_POST_APPROVED, MENTION, GROUP_KICK,
    STORY_REACT, STORY_REPLY
}
